nelmio_api_doc:
    documentation:
        info:
            title: Budget Manager API
            description: |
                MVP REST API for Budget Manager application.
                
                This API allows you to manage personal budgets and transactions.
                Authentication is required using JWT tokens.
                
                ## Getting Started
                
                1. Register a new user account using `/api/register`
                2. Login with your credentials using `/api/login` to get a JWT token
                3. Include the JWT token in the Authorization header: `Bearer {your-jwt-token}`
                4. Start managing your budgets and transactions!
                
                ## Test Account
                
                You can use the following test account:
                - **Email**: test@example.com
                - **Password**: password123
            version: 1.0.0
            contact:
                name: Budget Manager Team
                email: support@budgetmanager.local
        servers:
            - url: /api
              description: API base path
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: 'Enter your JWT token in the format: Bearer {token}'
    areas:
        path_patterns:
            - ^/api(?!/docs$)
    models:
        use_jms: false